name: build

on:
  push:
    branches: 
      - main
      - dev
      - 'release/**'
  pull_request:
    branches: 
      - main
      - dev
      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 8, 11, 16, 19 ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
          cache: maven
      - run: mvn -B install --no-transfer-progress
